#!/bin/bash

echo "Environment Variables to Set in Vercel Dashboard:"
echo "=============================================="
echo ""
echo "Go to your Vercel project dashboard and add these environment variables:"
echo ""
echo "Variable Name: GOOGLE_DRIVE_API_KEY"
echo "Variable Value: AIzaSyD88AMOydwdkfRWu9Rfm6BlhUUUKQC6WGw"
echo ""
echo "Variable Name: GOOGLE_DRIVE_FOLDER_FLOWER" 
echo "Variable Value: 1ZcE9R3FMvZa5TRp8HfAHo-K7dAD5IfmL"
echo ""
echo "Variable Name: GOOGLE_DRIVE_FOLDER_HERB"
echo "Variable Value: 1aVMw8n51wCndrlUb8xG5cRjsMvBnON7n"
echo ""
echo "Variable Name: GOOGLE_DRIVE_FOLDER_VEGETABLE" 
echo "Variable Value: 1rmv-7k70qL_fR1efsKa_t28I22pLKzf_"
echo ""
echo "Security Note: These will be securely stored by Vercel"
echo "After adding these, redeploy your Vercel project"
echo ""
echo "Next Steps:"
echo "1. Enable Google Drive API in Google Cloud Console"
echo "2. Make sure folders are publicly accessible or use service account"
echo "3. Test the API endpoints after deployment"