"""Add recommendation engine fields to plants

Revision ID: 65cb6b235291
Revises: 547ce03969cf
Create Date: 2025-09-12 01:55:58.936661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cb6b235291'
down_revision: Union[str, None] = '547ce03969cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('sun_need', sa.String(length=50), nullable=True))
    op.add_column('plants', sa.Column('indoor_ok', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('container_ok', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('edible', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('sowing_months_by_climate', sa.JSON(), nullable=True))
    op.add_column('plants', sa.Column('maintainability_score', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('time_to_maturity_days', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('habit', sa.String(length=100), nullable=True))
    op.add_column('plants', sa.Column('fragrant', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('flower_colors', sa.JSON(), nullable=True))
    op.add_column('plants', sa.Column('sowing_depth_mm', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('spacing_cm', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('sowing_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'sowing_method')
    op.drop_column('plants', 'spacing_cm')
    op.drop_column('plants', 'sowing_depth_mm')
    op.drop_column('plants', 'flower_colors')
    op.drop_column('plants', 'fragrant')
    op.drop_column('plants', 'habit')
    op.drop_column('plants', 'time_to_maturity_days')
    op.drop_column('plants', 'maintainability_score')
    op.drop_column('plants', 'sowing_months_by_climate')
    op.drop_column('plants', 'edible')
    op.drop_column('plants', 'container_ok')
    op.drop_column('plants', 'indoor_ok')
    op.drop_column('plants', 'sun_need')
    # ### end Alembic commands ###
